name: GitHub Actions Demo
on: [push]
jobs:
  structurizr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      -  uses:  aidmax/structurizr-cli-action@v0.2.0
         with:
           args: 'export -workspace workspace.dsl -format websequencediagrams'
          
         
