name: GitHub Actions Demo
on: [push]
jobs:
  structurizr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: extenda/structurizr-to-png
        with:
          working-directory: docs
          github-token: ${{ secrets.GITHUB_TOKEN }}
