name: structurizr
on:
  push:
    paths: 'docs/*.dsl'

jobs:
  structurizr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: extenda/structurizr-to-dsl@v0
        with:
          working-directory: docs
          github-token: ${{ secrets.GITHUB_TOKEN }}
