name: GitHub Actions Demo
on: [push]
jobs:
  structurizr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      -  uses: gilbertotcc/structurizr-action@v1
         with:
           args: 'export --workspace architecture.dsl --format json --output ./'
          
         
